### ISSUE TITLE
Option to change message body content

### ISSUE THREAD

**Issue by Saulios** [LilSpazJoekp/discord-relay#3]
### Describe the solution you'd like

Instead of the default ‘new post by u/user’ text, I would like to be able to add other things, such as the title of the submission, to the message. This makes the message more informative.

**Comment by LilSpazJoekp** [comment]
This was done intentionally due to Reddit's deletion policy. If I allow including any extra details I will have to implement deletion handlers and the message in Discord would be deleted if the user deletes their post/comment.
